# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import persistence_service_pb2 as persistence__service__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in persistence_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersistenceServiceStub(object):
    """The Persistence Service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreTerrain = channel.unary_unary(
                '/persistence.PersistenceService/StoreTerrain',
                request_serializer=persistence__service__pb2.StoreTerrainRequest.SerializeToString,
                response_deserializer=persistence__service__pb2.StoreTerrainResponse.FromString,
                _registered_method=True)
        self.RetrieveTerrain = channel.unary_unary(
                '/persistence.PersistenceService/RetrieveTerrain',
                request_serializer=persistence__service__pb2.RetrieveTerrainRequest.SerializeToString,
                response_deserializer=persistence__service__pb2.RetrieveTerrainResponse.FromString,
                _registered_method=True)


class PersistenceServiceServicer(object):
    """The Persistence Service definition.
    """

    def StoreTerrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveTerrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersistenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreTerrain': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTerrain,
                    request_deserializer=persistence__service__pb2.StoreTerrainRequest.FromString,
                    response_serializer=persistence__service__pb2.StoreTerrainResponse.SerializeToString,
            ),
            'RetrieveTerrain': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveTerrain,
                    request_deserializer=persistence__service__pb2.RetrieveTerrainRequest.FromString,
                    response_serializer=persistence__service__pb2.RetrieveTerrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'persistence.PersistenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('persistence.PersistenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersistenceService(object):
    """The Persistence Service definition.
    """

    @staticmethod
    def StoreTerrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/persistence.PersistenceService/StoreTerrain',
            persistence__service__pb2.StoreTerrainRequest.SerializeToString,
            persistence__service__pb2.StoreTerrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveTerrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/persistence.PersistenceService/RetrieveTerrain',
            persistence__service__pb2.RetrieveTerrainRequest.SerializeToString,
            persistence__service__pb2.RetrieveTerrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
