# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: persistence_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'persistence_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19persistence_service.proto\x12\x0bpersistence\">\n\x13StoreTerrainRequest\x12\'\n\x05tiles\x18\x01 \x03(\x0b\x32\x18.persistence.TerrainTile\"*\n\x14StoreTerrainResponse\x12\x12\n\nterrain_id\x18\x01 \x01(\t\",\n\x16RetrieveTerrainRequest\x12\x12\n\nterrain_id\x18\x01 \x01(\t\"B\n\x17RetrieveTerrainResponse\x12\'\n\x05tiles\x18\x01 \x03(\x0b\x32\x18.persistence.TerrainTile\"9\n\x0bTerrainTile\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x14\n\x0cterrain_type\x18\x03 \x01(\t2\xc7\x01\n\x12PersistenceService\x12S\n\x0cStoreTerrain\x12 .persistence.StoreTerrainRequest\x1a!.persistence.StoreTerrainResponse\x12\\\n\x0fRetrieveTerrain\x12#.persistence.RetrieveTerrainRequest\x1a$.persistence.RetrieveTerrainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persistence_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORETERRAINREQUEST']._serialized_start=42
  _globals['_STORETERRAINREQUEST']._serialized_end=104
  _globals['_STORETERRAINRESPONSE']._serialized_start=106
  _globals['_STORETERRAINRESPONSE']._serialized_end=148
  _globals['_RETRIEVETERRAINREQUEST']._serialized_start=150
  _globals['_RETRIEVETERRAINREQUEST']._serialized_end=194
  _globals['_RETRIEVETERRAINRESPONSE']._serialized_start=196
  _globals['_RETRIEVETERRAINRESPONSE']._serialized_end=262
  _globals['_TERRAINTILE']._serialized_start=264
  _globals['_TERRAINTILE']._serialized_end=321
  _globals['_PERSISTENCESERVICE']._serialized_start=324
  _globals['_PERSISTENCESERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
