admin:
  # Redirect admin access logs to stdout instead of a file
  access_log_path: /dev/stdout

static_resources:
  listeners:
    - name: listener_https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 3000  # HTTPS port for client-to-Envoy communication
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "certs/localhost.pem"
                    private_key:
                      filename: "certs/localhost-key.pem"
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_https
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      cors:
                        allow_origin_string_match:
                          - exact: "https://localhost:3000"
                          - exact: "https://localhost:3001"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: content-type,x-grpc-web,x-user-agent,grpc-timeout,authorization,x-requested-with
                        expose_headers: grpc-status,grpc-message,content-length,x-kuma-revision
                        max_age: "1728000"
                        allow_credentials: true  # Ensure credentials are allowed if needed
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: terrain_generation_service
                http_filters:
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                      filter_enabled:
                        default_value:
                          numerator: 100
                          denominator: HUNDRED
                      shadow_enabled:
                        default_value:
                          numerator: 0
                          denominator: HUNDRED
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: terrain_generation_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}  # Enable HTTP/2
      lb_policy: round_robin
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: "certs/localhost.pem"
                private_key:
                  filename: "certs/localhost-key.pem"
      load_assignment:
        cluster_name: terrain_generation_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 50051




# static_resources:
#   listeners:
#     - name: listener_0
#       address:
#         socket_address:
#           address: 0.0.0.0
#           port_value: 8090
#       filter_chains:
#         - filters:
#             - name: envoy.filters.network.http_connection_manager
#               typed_config:
#                 "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
#                 stat_prefix: ingress_http
#                 codec_type: AUTO
#                 route_config:
#                   name: local_route
#                   virtual_hosts:
#                     - name: grpc_services
#                       domains: ["*"]
#                       routes:
#                         - match:
#                             prefix: "/terrain.TerrainGenerationService/"
#                           route:
#                             cluster: terrain_generation_service
#                         - match:
#                             prefix: "/grpc.reflection.v1alpha.ServerReflection/"
#                           route:
#                             cluster: terrain_generation_service
#                 http_filters:
#                   - name: envoy.filters.http.grpc_web
#                     typed_config:
#                       "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
#                   - name: envoy.filters.http.router
#   clusters:
#     - name: terrain_generation_service
#       connect_timeout: 0.25s
#       type: STRICT_DNS
#       lb_policy: ROUND_ROBIN
#       load_assignment:
#         cluster_name: terrain_generation_service
#         endpoints:
#           - lb_endpoints:
#               - endpoint:
#                   address:
#                     socket_address:
#                       address: localhost
#                       port_value: 50051