name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - master  # Triggers on PRs targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install os dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev libgirepository1.0-dev libgrpc-dev libprotobuf-dev libgrpc++-dev 
        sudo apt-get install -y build-essential autoconf libtool pkg-config cmake doxygen
        sudo apt-get install -y libgrpc-dev protobuf-compiler protobuf-compiler-grpc

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_services/terrain_generation/requirements.txt
        pip install -r python_services/persistence/requirements.txt
        
    - name: Install javascript dependencies
      run: |
        cd javascript_services/vie_ui
        npm install
        cd ../..

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.3'  # Specify the required CMake version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Run tests with Coverage
      working-directory: build
      run: make run_tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Start application
      run: ./script/start.sh
    
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        cmd_options: '-a'
        target: 'http://localhost:3000'
    # - name: Zap scan
    #   run: |
    #     docker run -d --name zap -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true

    # - name: Wait for ZAP to start
    #   run: |
    #       until curl -s http://localhost:8090/JSON/core/view/version/; do
    #         echo "Waiting for ZAP to start..."
    #         sleep 5
    #       done

    # - name: Run ZAP scan
    #   run: |
    #       docker exec zap zap-cli -p 8090 open-url http://localhost:3000
    #       docker exec zap zap-cli -p 8090 active-scan http://localhost:3000
    #       docker exec zap zap-cli -p 8090 report -o zap_report.html -f html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
          name: zap-report
          path: zap_report.html

    - name: Stop ZAP
      run: docker stop zap
