name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - master  # Triggers on PRs targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install non-python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev libgirepository1.0-dev libgrpc-dev libprotobuf-dev libgrpc++-dev 
        sudo apt-get install -y build-essential autoconf libtool pkg-config cmake doxygen
        sudo apt-get install -y libgrpc-dev protobuf-compiler protobuf-compiler-grpc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_services/terrain_generation/requirements.txt
        pip install -r python_services/persistence/requirements.txt
        
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.3'  # Specify the required CMake version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Run tests with Coverage
      working-directory: build
      run: make run_tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    # - name: Install SonarScanner
    #   run: |
    #     curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
    #     unzip sonar-scanner-cli.zip
    #     export PATH="$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin"

    # - name: Upload coverage to SonarCloud
    #   run: |
    #     sonar-scanner
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
